
services:
 
  # -----------------------------------------------------------------
  # 1. API GATEWAY (Gerbang Publik Utama - Port 8010)
  # -----------------------------------------------------------------
  api-gateway:
    build: ./service/api-gateway
    container_name: ijazah-api-gateway
    restart: always
    ports:
      - "8010:3000"                   
    depends_on:
      - auth-service
      - inbound-service
      - master-data-service
      - dashboard-service
      - akademik-service
      - approval-service
      - template-service
      - document-service
      - qr-service
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3002
      - INBOUND_SERVICE_URL=http://inbound-service:3003
      - MASTER_DATA_SERVICE_URL=http://master-data-service:3004
      - AKADEMIK_SERVICE_URL=http://akademik-service:3005
      - APPROVAL_SERVICE_URL=http://approval-service:3006
      - DASHBOARD_SERVICE_URL=http://dashboard-service:3007
      - TEMPLATE_SERVICE_URL=http://template-service:3008 
      - DOCUMENT_SERVICE_URL=http://document-service:3009 
      - QR_SERVICE_URL=http://qr-service:3010 
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - PUBLIC_BASE_URL="http://103.158.196.32:8010"

  # -----------------------------------------------------------------
  # 2. AUTH SERVICE (Internal)
  # -----------------------------------------------------------------
  auth-service:
    build: ./service/auth-service
    container_name: ijazah-service-auth
    restart: always
    environment:
      - PORT=3002                                          
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

  # -----------------------------------------------------------------
  # 3. INBOUND SERVICE (Internal)
  # -----------------------------------------------------------------
  inbound-service:
    build: ./service/inbound-service
    container_name: ijazah-service-inbound
    restart: always
    environment:
      - PORT=3003                                        
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

  # -----------------------------------------------------------------
  # 4. MASTER DATA SERVICE (Internal)
  # -----------------------------------------------------------------
  master-data-service:
    build: ./service/master-data-service    
    container_name: ijazah-service-masterdata
    restart: always
    environment:
      - PORT=3004
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

  # -----------------------------------------------------------------
  # 5. AKADEMIK SERVICE (Internal)  
  # -----------------------------------------------------------------
  akademik-service:
    build:
      context: ./service/akademik-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: ijazah-service-akademik
    restart: always
    environment:
      - PORT=3005
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  # -----------------------------------------------------------------
  # 6. APPROVAL SERVICE (Internal)
  # -----------------------------------------------------------------
  approval-service:
    build:
      context: ./service/approval-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: ijazah-service-approval
    restart: always
    environment:
      - PORT=3006
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

 
 # -----------------------------------------------------------------
  # 7. DASHBOARD SERVICE (Internal)
  # -----------------------------------------------------------------
  dashboard-service:
    build:
      context: ./service/dashboard-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: ijazah-service-dashboard
    restart: always
    environment:
      - PORT=3007
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

# -----------------------------------------------------------------
  # 8. Template SERVICE (Internal)
  # -----------------------------------------------------------------
  template-service:
    build:
      context: ./service/template-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: ijazah-service-template
    restart: always
    environment:
      - PORT=3008
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - PUBLIC_BASE_URL="http://103.158.196.32:8010"
      - INTERNAL_SERVICE_KEY="ijazahTranskrip_internal_service_secret"


# -----------------------------------------------------------------
  # 9. DOCUMENT SERVICE (Internal)
  # -----------------------------------------------------------------

  document-service:
    build:
      context: ./service/document-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: ijazah-service-document
    restart: always
    environment:
      - PORT=3009
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - PUBLIC_BASE_URL="http://103.158.196.32:8010"
      - INTERNAL_SERVICE_KEY="ijazahTranskrip_internal_service_secret"
      - AKADEMIK_SERVICE_URL="http://localhost:3005"
      - TEMPLATE_SERVICE_URL="http://localhost:3008"

# -----------------------------------------------------------------
  # 10. QR SERVICE (Internal)
  # -----------------------------------------------------------------
  
document-service:
    build:
      context: ./service/qr-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: ijazah-service-qr
    restart: always
    environment:
      - PORT=3010
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - PUBLIC_BASE_URL="http://103.158.196.32:8010"
      - INTERNAL_SERVICE_KEY="ijazahTranskrip_internal_service_secret"