version: '3.8'

services:
 
  api-gateway:
    build: ./service/api-gateway
    container_name: ijazah-api-gateway
    restart: always
    ports:
      - "7000:3000"                   
    depends_on:
      - auth-service
      - inbound-service
      - master-data-service
      - dashboard-service
      - approval-service

    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3002
      - INBOUND_SERVICE_URL=http://inbound-service:3003
      - MASTER_DATA_SERVICE_URL=http://master-data-service:3004
      - DASHBOARD_SERVICE_URL=http://dashboard-service:3007
      - APPROVAL_SERVICE_URL=http://approval-service:3006

  # -----------------------------------------------------------------
  # 2. AUTH SERVICE (Internal)
  # -----------------------------------------------------------------
  auth-service:
    build: ./service/auth-service
    container_name: ijazah-service-auth
    restart: always
    environment:
      - PORT=3002                          
      - DATABASE_URL=postgresql://neondb_owner:npg_n4fkcyZXH0EY@ep-noisy-union-aomnndsf-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=verify-full&channel_binding=require

  # -----------------------------------------------------------------
  # 3. INBOUND SERVICE (Internal)
  # -----------------------------------------------------------------
  inbound-service:
    build: ./service/inbound-service
    container_name: ijazah-service-inbound
    restart: always
    environment:
      - PORT=3003                        
      - DATABASE_URL=postgresql://neondb_owner:npg_n4fkcyZXH0EY@ep-noisy-union-aomnndsf-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=verify-full&channel_binding=require

  # -----------------------------------------------------------------
  # 4. MASTER DATA SERVICE (Internal)
  # -----------------------------------------------------------------
  master-data-service:
    build: ./service/master-data-service    
    container_name: ijazah-service-masterdata
    restart: always
    environment:
      - PORT=3004
      - DATABASE_URL=postgresql://neondb_owner:npg_n4fkcyZXH0EY@ep-noisy-union-aomnndsf-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=verify-full&channel_binding=require

  # -----------------------------------------------------------------
  # 5. DASHBOARD SERVICE (Internal)
  # -----------------------------------------------------------------
  dashboard-service:
    build:
      context: ./service/dashboard-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://neondb_owner:npg_n4fkcyZXH0EY@ep-noisy-union-aomnndsf-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=verify-full&channel_binding=require
    container_name: ijazah-service-dashboard
    restart: always
    environment:
      - PORT=3007
      - DATABASE_URL=postgresql://neondb_owner:npg_n4fkcyZXH0EY@ep-noisy-union-aomnndsf-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=verify-full&channel_binding=require

  # -----------------------------------------------------------------
  # 6. APPROVAL SERVICE (Internal)
  # -----------------------------------------------------------------
  approval-service:
    build:
      context: ./service/approval-service
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://neondb_owner:npg_n4fkcyZXH0EY@ep-noisy-union-aomnndsf-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=verify-full&channel_binding=require
    container_name: ijazah-service-approval
    restart: always
    environment:
      - PORT=3006
      - DATABASE_URL=postgresql://neondb_owner:npg_n4fkcyZXH0EY@ep-noisy-union-aomnndsf-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=verify-full&channel_binding=require