// This file was generated by Prisma, and assumes you have installed the following:
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts", // <-- CUKUP TAMBAHKAN BARIS INI
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
  },
});