export const IJAZAH_PLACEHOLDERS = [
  {
    label: "Nama",
    placeholder: "{{nama}}",
    field: "mahasiswa.nama",
    type: "text",
  },
  {
    label: "Tempat & Tanggal Lahir",
    placeholder: "{{tempat_tanggal_lahir}}",
    field: "mahasiswa.tempat_tanggal_lahir",
    type: "text",
  },
  {
    label: "Nomor Pokok Mahasiswa",
    placeholder: "{{nomor_pokok_mahasiswa}}",
    field: "mahasiswa.nomor_pokok_mahasiswa",
    type: "text",
  },
  {
    label: "NIK",
    placeholder: "{{nik}}",
    field: "mahasiswa.nik",
    type: "text",
  },
  {
    label: "Fakultas",
    placeholder: "{{fakultas}}",
    field: "akademik.fakultas",
    type: "text",
  },
  {
    label: "Fakultas (English)",
    placeholder: "{{fakultas_en}}",
    field: "akademik.fakultas_en",
    type: "text",
  },
  {
    label: "Program Studi",
    placeholder: "{{program_studi}}",
    field: "akademik.program_studi",
    type: "text",
  },
  {
    label: "Program Studi (English)",
    placeholder: "{{program_studi_en}}",
    field: "akademik.program_studi_en",
    type: "text",
  },
  {
    label: "Program",
    placeholder: "{{program}}",
    field: "akademik.program",
    type: "text",
  },
  {
    label: "Program (English)",
    placeholder: "{{program_en}}",
    field: "akademik.program_en",
    type: "text",
  },
  {
    label: "Tanggal Kelulusan",
    placeholder: "{{tanggal_kelulusan}}",
    field: "akademik.tanggal_kelulusan_formatted",
    type: "text",
  },
  {
    label: "PISN",
    placeholder: "{{pisn}}",
    field: "mahasiswa.pisn",
    type: "text",
  },
  {
    label: "Nomor Seri Ijazah",
    placeholder: "{{nomor_seri_ijazah}}",
    field: "mahasiswa.nomor_seri_ijazah",
    type: "text",
  },
  {
    label: "Akreditasi AIPT",
    placeholder: "{{akreditasi_aipt}}",
    field: "akademik.akreditasi_aipt",
    type: "text",
  },
  {
    label: "Foto",
    placeholder: "{{foto}}",
    field: "mahasiswa.foto",
    type: "image",
  },
  {
    label: "QR Code",
    placeholder: "{{qr_code}}",
    field: "dokumen_placeholder.qr_code",
    type: "qr",
  },
  {
    label: "Gelar",
    placeholder: "{{gelar}}",
    field: "mahasiswa.gelar",
    type: "text",
  },
  {
    label: "Tanggal Terbit",
    placeholder: "{{tanggal_terbit}}",
    field: "dokumen_placeholder.tanggal_terbit_formatted",
    type: "text",
  },
  {
    label: "Nama Rektor",
    placeholder: "{{nama_rektor}}",
    field: "pejabat.nama_rektor",
    type: "text",
  },
  {
    label: "TTD Rektor",
    placeholder: "{{ttd_rektor}}",
    field: "assets.ttd_rektor",
    type: "image",
  },
  {
    label: "NIDN Rektor",
    placeholder: "{{nidn_rektor}}",
    field: "pejabat.nidn_rektor",
    type: "text",
  },
  {
    label: "Nama Dekan",
    placeholder: "{{nama_dekan}}",
    field: "pejabat.nama_dekan",
    type: "text",
  },
  {
    label: "TTD Dekan",
    placeholder: "{{ttd_dekan}}",
    field: "assets.ttd_dekan",
    type: "image",
  },
  {
    label: "NIDN Dekan",
    placeholder: "{{nidn_dekan}}",
    field: "pejabat.nidn_dekan",
    type: "text",
  },
  {
    label: "Paraf KATU Rektor",
    placeholder: "{{paraf_katu_rektor}}",
    field: "assets.paraf_katu_rektor",
    type: "image",
  },
  {
    label: "Paraf WAREK",
    placeholder: "{{paraf_warek}}",
    field: "assets.paraf_warek",
    type: "image",
  },
  {
    label: "Paraf KATU Fakultas",
    placeholder: "{{paraf_katu_fakultas}}",
    field: "assets.paraf_katu_fakultas",
    type: "image",
  },
  {
    label: "Paraf Wadek",
    placeholder: "{{paraf_wadek}}",
    field: "assets.paraf_wadek",
    type: "image",
  },
  {
    label: "Stempel Rektor",
    placeholder: "{{stempel_rektor}}",
    field: "assets.stempel_rektor",
    type: "image",
  },
  {
    label: "Stempel Dekan",
    placeholder: "{{stempel_dekan}}",
    field: "assets.stempel_dekan",
    type: "image",
  },
];

export const TRANSKRIP_PLACEHOLDERS = [
  {
    label: "Nomor",
    placeholder: "{{nomor}}",
    field: "dokumen_placeholder.nomor_dokumen",
    type: "text",
  },
  {
    label: "Nama",
    placeholder: "{{nama}}",
    field: "mahasiswa.nama",
    type: "text",
  },
  {
    label: "Tempat & Tanggal Lahir",
    placeholder: "{{tempat_tanggal_lahir}}",
    field: "mahasiswa.tempat_tanggal_lahir",
    type: "text",
  },
  {
    label: "Jenis Kelamin",
    placeholder: "{{jenis_kelamin}}",
    field: "mahasiswa.jenis_kelamin",
    type: "text",
  },
  {
    label: "Nomor Pokok Mahasiswa",
    placeholder: "{{nomor_pokok_mahasiswa}}",
    field: "mahasiswa.nomor_pokok_mahasiswa",
    type: "text",
  },
  {
    label: "NINA",
    placeholder: "{{nina}}",
    field: "mahasiswa.nina",
    type: "text",
  },
  {
    label: "NIK",
    placeholder: "{{nik}}",
    field: "mahasiswa.nik",
    type: "text",
  },
  {
    label: "Tahun Masuk",
    placeholder: "{{tahun_masuk}}",
    field: "mahasiswa.tahun_masuk",
    type: "text",
  },
  {
    label: "Program Pendidikan",
    placeholder: "{{program_pendidikan}}",
    field: "akademik.program",
    type: "text",
  },
  {
    label: "Fakultas",
    placeholder: "{{fakultas}}",
    field: "akademik.fakultas",
    type: "text",
  },
  {
    label: "Program Studi",
    placeholder: "{{program_studi}}",
    field: "akademik.program_studi",
    type: "text",
  },
  {
    label: "Nomor SK Akreditasi",
    placeholder: "{{nomor_sk_akreditasi}}",
    field: "akademik.nomor_sk_akreditasi",
    type: "text",
  },
  {
    label: "Status",
    placeholder: "{{status}}",
    field: "akademik.status_kelulusan",
    type: "text",
  },
  {
    label: "Tanggal Lulus",
    placeholder: "{{tanggal_lulus}}",
    field: "akademik.tanggal_kelulusan_formatted",
    type: "text",
  },
  {
    label: "Tabel Mata Kuliah",
    placeholder: "{{tabel_mata_kuliah}}",
    field: "transkrip",
    type: "table",
  },
  {
    label: "TTD Dekan",
    placeholder: "{{ttd_dekan}}",
    field: "assets.ttd_dekan",
    type: "image",
  },
  {
    label: "Nama Dekan",
    placeholder: "{{nama_dekan}}",
    field: "pejabat.nama_dekan",
    type: "text",
  },
  {
    label: "NIDN Dekan",
    placeholder: "{{nidn_dekan}}",
    field: "pejabat.nidn_dekan",
    type: "text",
  },
  {
    label: "Paraf KATU Fakultas",
    placeholder: "{{paraf_katu_fakultas}}",
    field: "assets.paraf_katu_fakultas",
    type: "image",
  },
  {
    label: "Paraf Kaprodi",
    placeholder: "{{paraf_kaprodi}}",
    field: "assets.paraf_kaprodi",
    type: "image",
  },
];